# Generated by Django 6.0.2 on 2026-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartegory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cartegory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
