# Generated by Django 6.0.2 on 2026-04-29 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_cartegory_options_item_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartegory',
            new_name='Category',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='items_item_categor_ac6954_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner'], name='items_item_owner_i_21c409_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at'], name='items_item_created_3cdd06_idx'),
        ),
    ]
